export const demoVehicles = [
  { make: 'Toyota', model: 'Camry', category: 'Sedan', price: 27999, quantity: 8 },
  { make: 'Honda', model: 'Accord', category: 'Sedan', price: 25950, quantity: 6 },
  { make: 'Toyota', model: 'Corolla', category: 'Sedan', price: 19990, quantity: 10 },
  { make: 'Honda', model: 'Civic', category: 'Sedan', price: 21950, quantity: 7 },
  { make: 'BMW', model: '3 Series', category: 'Sedan', price: 46900, quantity: 2 },
  { make: 'Audi', model: 'A4', category: 'Sedan', price: 42900, quantity: 3 },
  { make: 'Mercedes-Benz', model: 'C-Class', category: 'Sedan', price: 48900, quantity: 1 },
  { make: 'Ford', model: 'F-150', category: 'Truck', price: 48990, quantity: 4 },
  { make: 'Chevrolet', model: 'Silverado 1500', category: 'Truck', price: 45900, quantity: 5 },
  { make: 'Ram', model: '1500', category: 'Truck', price: 44950, quantity: 2 },
  { make: 'Jeep', model: 'Wrangler', category: 'SUV', price: 45999, quantity: 1 },
  { make: 'Honda', model: 'CR-V', category: 'SUV', price: 33950, quantity: 6 },
  { make: 'Toyota', model: 'RAV4', category: 'SUV', price: 32990, quantity: 9 },
  { make: 'Mazda', model: 'CX-5', category: 'SUV', price: 35800, quantity: 7 },
  { make: 'Subaru', model: 'Outback', category: 'Wagon', price: 31990, quantity: 5 },
  { make: 'Nissan', model: 'Rogue', category: 'SUV', price: 27990, quantity: 4 },
  { make: 'Kia', model: 'Sorento', category: 'SUV', price: 34900, quantity: 6 },
  { make: 'Lexus', model: 'RX', category: 'SUV', price: 54900, quantity: 2 },
  { make: 'Volvo', model: 'XC90', category: 'SUV', price: 62900, quantity: 1 },
  { make: 'Tesla', model: 'Model 3', category: 'Electric', price: 42990, quantity: 3 },
  { make: 'Tesla', model: 'Model Y', category: 'SUV', price: 53990, quantity: 4 },
  { make: 'Nissan', model: 'Leaf', category: 'Electric', price: 21999, quantity: 2 },
  { make: 'Hyundai', model: 'Kona Electric', category: 'Electric', price: 34900, quantity: 1 },
  { make: 'Ford', model: 'Mustang', category: 'Coupe', price: 37990, quantity: 3 },
  { make: 'Chevrolet', model: 'Camaro', category: 'Coupe', price: 35990, quantity: 2 },
  { make: 'Porsche', model: '911', category: 'Coupe', price: 99900, quantity: 1 },
  { make: 'Mazda', model: 'MX-5 Miata', category: 'Convertible', price: 27990, quantity: 2 },
  { make: 'Mini', model: 'Cooper', category: 'Hatchback', price: 23990, quantity: 4 },
  { make: 'Volkswagen', model: 'Golf', category: 'Hatchback', price: 22990, quantity: 3 },
  { make: 'Kia', model: 'Forte', category: 'Sedan', price: 18990, quantity: 6 },
  { make: 'Hyundai', model: 'Elantra', category: 'Sedan', price: 17990, quantity: 8 },
  { make: 'Honda', model: 'Odyssey', category: 'Minivan', price: 38990, quantity: 2 },
  { make: 'Chrysler', model: 'Pacifica', category: 'Minivan', price: 36990, quantity: 0 },
] as const;

